version: 0.1

phases:
  install:
    commands:
      - |
        npm install -g serverless
        npm install
  build:
    commands:
      - |
        sls sam export --output ./.serverless/sam-template.yml
        aws cloudformation package \
          --template-file ./.serverless/sam-template.yml \
          --s3-bucket test-serverless-deployments-arh \
          --output-template-file ./.serverless/packaged.yml

artifacts:
  files:
    - .serverless/*
  discard-paths: yes
