version: 0.1

phases:
  install:
    commands:
      - |
        npm install -g serverless
        npm install
  build:
    commands:
      - |
        [ -d .sam ] || mkdir .sam
        sls sam export --output ./.sam/sam-template.yml
        aws cloudformation package \
          --template-file ./.sam/sam-template.yml \
          --s3-bucket test-serverless-deployments-arh \
          --output-template-file ./.sam/packaged.yml

artifacts:
  files:
    - .sam/*
  discard-paths: yes
